export const UrunData = [
  {
    id: 1,
    cathegory: "Gunluk buket",
    ismi: "Peony Demeti",
    stok: 8,
    fiyat: 450,
  },
  {
    id: 2,
    cathegory: "Gunluk buket",
    ismi: "Sabah Çiyi Buketi",
    stok: 3,
    fiyat: 480,
  },
  {
    id: 3,
    cathegory: "Gunluk buket",
    ismi: "Mercan Anemon",
    stok: 0,
    fiyat: 500,
  },
  {
    id: 4,
    cathegory: "Saksı Çiçegi",
    ismi: "Zeytin Dalı Saksı",
    stok: 12,
    fiyat: 380,
  },
  {
    id: 5,
    cathegory: "Saksı Çiçegi",
    ismi: "Minik Sukulent",
    stok: 0,
    fiyat: 400,
  },
  {
    id: 6,
    cathegory: "Saksı Çiçegi",
    ismi: "Lavanta Saksısı",
    stok: 4,
    fiyat: 670,
  },
  {
    id: 7,
    cathegory: "Özel Gün",
    ismi: "Yıldönümü Özel",
    stok: 5,
    fiyat: 650,
  },
  {
    id: 8,
    cathegory: "Özel Gün",
    ismi: "Dogum Gunu Şatosu",
    stok: 0,
    fiyat: 700,
  },
  {
    id: 9,
    cathegory: "Özel Gün",
    ismi: "Sade beyazlar",
    stok: 4,
    fiyat: 590,
  },
];
